### ISSUE TITLE
add SSL udp-proxy problem

### ISSUE THREAD

**Issue by eazaika** [meefik/ITMOproctor#39]
Добавив nginx с upstream-бэкэндом node.js, столкнулись с неожиданной проблемой: теряются udp-пакеты. Видео и рабочий стол отправляются на сервер, но вот получить их клиенту уже не удается. У nginx, по слухам, есть механизм проксирования udp-пакетов (через stream), однако чтобы пересобрать nginx с флагом --with-stream, включающим данный функционал, версия nginx должна быть 1.9+, тогда как на ubuntu 14.04, указанной в requirements, актуальная stable-версия 1.4.6. 

Как эта проблема решена на https://proctor.ifmo.ru?

**Comment by meefik** [comment]
Если сервер находится за NAT, то для корректной маршрутизации UDP видеотрафика нужно использовать TURN сервер. Либо на сервере KMS должен публичный IP-адрес.

**Comment by eazaika** [comment]
Kurento на том же сервере, что и node.js - ip публичный (proctor.etu.ru 194.85.169.73). При попытке передачи рабочего стола получаем:
`WebSocket connection to 'wss://proctor.etu.ru/socket.io/?EIO=3&transport=websocket&sid=q8apZLq6xNbawtIgAAAF' failed: Error during WebSocket handshake: Unexpected response code: 400` universalModuleDefinition
и
`DOMException: Invalid state` webcall.js

**Comment by meefik** [comment]
Можно попробовать настроить nginx, добавив правильный проброс WS:
```
    location /socket.io {
        proxy_pass http://127.0.0.1:3000;
        proxy_redirect off;

        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-By $server_addr:$server_port;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
```

**Comment by eazaika** [comment]
Собственно, даже при такой конфигурации:
`location / {
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header Host $http_host;
            proxy_set_header X-NginX-Proxy true;
            proxy_pass http://127.0.0.1:3000;
            proxy_redirect off;
        }`
получаем `DOMException: Invalid state` webcall.js
Вопрос еще: должен ли KMS работать c wss вместо ws? Впрочем, на проблему на практике это никак не влияет:
` "net" : {
      "websocket": {
        "port": 8888,
        "secure": {
          "port": 8433,
          "certificate": "/etc/letsencrypt/live/proctor.etu.ru/fullchain.pem",
          "password": ""
        },`
Само же приложение не нужно на https переводить?

**Comment by meefik** [comment]
Вообще, wss не нужен, т.к. kurento-client и KMS находятся на одном сервере и запрос должен идти к KMS не через nginx, а напрямую на адрес ws://localhost:8888/kurento

**Comment by eazaika** [comment]
Окей, видео с камеры теперь клиенту возвращается (просто kms не стартовал), но рабочий стол по-прежнему не транслируется: сразу идет принудительное закрытие соединения:
```
DOMException: Invalid state
onError @ webcall.js:78
(anonymous) @ webcall.js:236
setCallState:NO_CALL
webcall.js:199 Senging message: {"id":"stop"}
webcall.js:127 setCallState:PROCESSING_CALL
```
output.log:
```
2018-05-22T10:40:52.075Z - debug: Connection 13 received message: {"id":"stop"}
```

**Comment by meefik** [comment]
Трансляция экрана работает только через приложение или расширение для Chrome.

**Comment by eazaika** [comment]
Спасибо!

**Comment by eazaika** [comment]
Вы же используете TURN, да? Сервер, получается, разворачивать необходимо в public сети - серьезно это все задерживает трафик на практике?

**Comment by meefik** [comment]
Да, TURN используется, особенно если сервер KMS за NAT. На качество трафика особо не влияет, но это от сервера зависит, видимо.

**Comment by ximik666** [comment]
Добрый день! А может кто-нибуlь скинуть рабочий вариант настроек с nginx?

**Comment by eazaika** [comment]
@ximik666,
вот с такими сейчас работаем:
```
upstream app_proctor {
        server 127.0.0.1:3000;
        #keepalive 8;
}
server {
        root /<your_pass>/ITMOproctor;
        index index.html;
        server_name your-site.sub.ru www.your-site.sub.ru;

        location / {
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";
                #proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-By $server_addr:$server_port;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_set_header Host $host;
                #proxy_set_header X-NginX-Proxy true;

                proxy_pass http://app_proctor;
                proxy_redirect off;
        }

        location ^~ /public {
                root /<your_pass>/ITMOproctor/public;
        }

        listen 443 ssl; # managed by Certbot
        ssl_certificate /etc/letsencrypt/live/your-site.sub.ru/fullchain.pem; # managed by Certbot
        ssl_certificate_key /etc/letsencrypt/live/your-site.sub.ru/privkey.pem; # managed by Certbot
        include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
        ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

        #Redirect non-https traffic to https
        if ($scheme != "https") {
                 return 301 https://$host$request_uri;
        } # managed by Certbot
}

server {
        if ($host = www.your-site.sub.ru) {
                return 301 https://$host$request_uri;
        } # managed by Certbot

        if ($host = your-site.sub.ru) {
                return 301 https://$host$request_uri;
        } # managed by Certbot

        listen 80 default_server;
        server_name your-site.sub.ru www.your-site.sub.ru;
        return 404; # managed by Certbot
}
```

**Comment by ximik666** [comment]
А как же kurento?
Я так понимаю на внешнем nginx такой конфиг? А как udp обошли?

**Comment by eazaika** [comment]
@ximik666,
так как через наш NAT пакеты udp теряют адресата, мы используем для этого сервера внешний IP.
