### ISSUE TITLE
cannot run in wd proctor-server@0.8.0

### ISSUE THREAD

**Issue by egorsmorgunov** [meefik/ITMOproctor#41]
# node -v
v12.18.2
# git clone https://github.com/meefik/ITMOproctor.git
...done.
# cd ./ITMOproctor
# npm install

> bufferutil@4.0.1 install /www/ITMOproctor/node_modules/bufferutil
> node-gyp-build

> ws@0.4.32 install /www/ITMOproctor/node_modules/websocket-stream/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

make: Entering directory '/www/ITMOproctor/node_modules/websocket-stream/node_modules/ws/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
bufferutil.target.mk:113: recipe for target 'Release/obj.target/bufferutil/src/bufferutil.o' failed
make: Leaving directory '/www/ITMOproctor/node_modules/websocket-stream/node_modules/ws/build'

> ejs@3.1.3 postinstall /www/ITMOproctor/node_modules/ejs
> node --harmony ./postinstall.js

Thank you for installing EJS: built with the Jake JavaScript build tool (https://jakejs.com/)

> nodemailer@6.4.6 postinstall /www/ITMOproctor/node_modules/nodemailer
> node -e "try{require('./postinstall')}catch(e){}"

=== Nodemailer 6.4.6 ===

Thank you for using Nodemailer for your email sending needs! While Nodemailer
itself is mostly meant to be a SMTP client there are other related projects in
the Nodemailer project as well.

For example:
> IMAP API (  https://imapapi.com  ) is a server application to easily access
IMAP accounts via REST API
> NodemailerApp (  https://nodemailer.com/app/  ) is a cross platform GUI app to
debug emails

npm WARN lifecycle proctor-server@0.8.0~postinstall: cannot run in wd proctor-server@0.8.0 cd ./public && bower install (wd=/www/ITMOproctor)
added 643 packages from 400 contributors and audited 643 packages in 28.497s

63 packages are looking for funding
  run `npm fund` for details

found 53 vulnerabilities (51 low, 2 high)
  run `npm audit fix` to fix them, or `npm audit` for details

**Comment by meefik** [comment]
Обновлены зависимости, сборка выполняется без ошибок.
