### ISSUE TITLE
после npm start в консоли ошибок нет, но пустая страница по localhost:3000 с title "ITMOproctor"

### ISSUE THREAD

**Issue by jhd235** [meefik/ITMOproctor#44]
после npm start в консоли ошибок нет, но пустая страница по localhost:3000 с title "ITMOproctor" как на приложенном скриншоте
![Screenshot from 2020-09-03 12-11-41](https://user-images.githubusercontent.com/5977132/92216312-92ee4e00-eeaf-11ea-80ec-b8f4d88c39a2.png)

**Comment by Covgit19** [comment]
Thks I'll try it later

**Comment by Covgit19** [comment]
Ok I'll try it and hopefully it will solve the problem

Den fre 4 sep. 2020 10:08YERMEK NAURZALY <notifications@github.com> skrev:

**Comment by VasSpirit** [comment]
CTRL + F5

**Comment by VasSpirit** [comment]
CTRL + F5
Или команда запущена с под пользователем с правами root

**Comment by kreonix1** [comment]
> 
> 
> CTRL + F5
> Или команда запущена с под пользователем с правами root

Добрый день, и под root и другой пользователь одно и тоже, пустая страница.... 
нельзя ли подробнее про CTRL+F5 )))

**Comment by meefik** [comment]
Обновлены зависимости, вероятно, это исправит проблему.
