### ISSUE TITLE
Proctoring Client Side Apps

### ISSUE THREAD

**Issue by jhd235** [meefik/ITMOproctor#46]
https://github.com/meefik/ITMOproctor

https://docs.google.com/document/d/15fsEL3sHCGuJ9_rSuFprQXP--WXb9Ct-PzayBXvxWp0/preview
https://docs.google.com/document/d/1EbW52RQLdgwkRwJa_HgzP-nqU_860bPQuMZZ-ns1Hmc/preview

Вопрос: как сконфигурировать это клиентское приложение на произвольный адрес сервера прокторинга.
Сервер прокторинга это локальный сервер из https://github.com/meefik/ITMOproctor.
Клиентское приложение по ссылке выше не имеет в архиве конфигурационных файлов для указания адреса сервера прокторинга. Само клиентское приложение не имеет интерфейса настроек для указания сервера прокторинга. Нет исходников клиентского приложения.
![git links](https://user-images.githubusercontent.com/5977132/99901693-537b1500-2cda-11eb-90f6-1b4e8281f102.JPG)
![client](https://user-images.githubusercontent.com/5977132/99901697-5bd35000-2cda-11eb-9580-7ae1c50c8b84.JPG)
![VirtualBox_ubuntu16desktop_22_11_2020_16_09_33](https://user-images.githubusercontent.com/5977132/99902136-401d7900-2cdd-11eb-80d7-ca900d862f8e.png)

Рахмет, Ермек.
https://github.com/jhd235
Telegram: @jhd235

**Comment by meefik** [comment]
Изменить адрес страртовой страницы приложения можно в файле `app-nw/package.json`, поле `homepage`.
